using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace MyApp.OpenAi.Models {
    public class CreateAnswerRequest : IParsable {
        /// <summary>List of documents from which the answer for the input `question` should be derived. If this is an empty list, the question will be answered based on the question-answer examples.You should specify either `documents` or a `file`, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Documents { get; set; }
#nullable restore
#else
        public List<string> Documents { get; set; }
#endif
        /// <summary>List of (question, answer) pairs that will help steer the model towards the tone and answer format you&apos;d like. We recommend adding 2 to 3 examples.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Examples { get; set; }
#nullable restore
#else
        public List<string> Examples { get; set; }
#endif
        /// <summary>A text snippet containing the contextual information used to generate the answers for the `examples` you provide.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExamplesContext { get; set; }
#nullable restore
#else
        public string ExamplesContext { get; set; }
#endif
        /// <summary>The ID of an uploaded file that contains documents to search over. See [upload file](/docs/api-reference/files/upload) for how to upload a file of the desired format and purpose.You should specify either `documents` or a `file`, but not both.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? File { get; set; }
#nullable restore
#else
        public string File { get; set; }
#endif
        /// <summary>Modify the likelihood of specified tokens appearing in the completion.Accepts a json object that maps tokens (specified by their token ID in the GPT tokenizer) to an associated bias value from -100 to 100. You can use this [tokenizer tool](/tokenizer?view=bpe) (which works for both GPT-2 and GPT-3) to convert text to token IDs. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.As an example, you can pass `{&quot;50256&quot;: -100}` to prevent the &lt;|endoftext|&gt; token from being generated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public CreateAnswerRequest_logit_bias? LogitBias { get; set; }
#nullable restore
#else
        public CreateAnswerRequest_logit_bias LogitBias { get; set; }
#endif
        /// <summary>Include the log probabilities on the `logprobs` most likely tokens, as well the chosen tokens. For example, if `logprobs` is 5, the API will return a list of the 5 most likely tokens. The API will always return the `logprob` of the sampled token, so there may be up to `logprobs+1` elements in the response.The maximum value for `logprobs` is 5. If you need more than this, please contact us through our [Help center](https://help.openai.com) and describe your use case.When `logprobs` is set, `completion` will be automatically added into `expand` to get the logprobs.</summary>
        public int? Logprobs { get; set; }
        /// <summary>The maximum number of documents to be ranked by [Search](/docs/api-reference/searches/create) when using `file`. Setting it to a higher value leads to improved accuracy but with increased latency and cost.</summary>
        public int? MaxRerank { get; set; }
        /// <summary>The maximum number of tokens allowed for the generated answer</summary>
        public int? MaxTokens { get; set; }
        /// <summary>ID of the model to use for completion. You can select one of `ada`, `babbage`, `curie`, or `davinci`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>How many answers to generate for each question.</summary>
        public int? N { get; set; }
        /// <summary>Question to get answered.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Question { get; set; }
#nullable restore
#else
        public string Question { get; set; }
#endif
        /// <summary>A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a &quot;metadata&quot; field.This flag only takes effect when `file` is set.</summary>
        public bool? ReturnMetadata { get; set; }
        /// <summary>If set to `true`, the returned JSON will include a &quot;prompt&quot; field containing the final prompt that was used to request a completion. This is mainly useful for debugging purposes.</summary>
        public bool? ReturnPrompt { get; set; }
        /// <summary>ID of the model to use for [Search](/docs/api-reference/searches/create). You can select one of `ada`, `babbage`, `curie`, or `davinci`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SearchModel { get; set; }
#nullable restore
#else
        public string SearchModel { get; set; }
#endif
        /// <summary>Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Answers? Stop { get; set; }
#nullable restore
#else
        public Answers Stop { get; set; }
#endif
        /// <summary>What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic.</summary>
        public double? Temperature { get; set; }
        /// <summary>A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](/docs/guides/safety-best-practices/end-user-ids).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? User { get; set; }
#nullable restore
#else
        public string User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new CreateAnswerRequest and sets the default values.
        /// </summary>
        public CreateAnswerRequest() {
            SearchModel = "ada";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static CreateAnswerRequest CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new CreateAnswerRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"documents", n => { Documents = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"examples", n => { Examples = n.GetCollectionOfPrimitiveValues<string>()?.ToList(); } },
                {"examples_context", n => { ExamplesContext = n.GetStringValue(); } },
                {"file", n => { File = n.GetStringValue(); } },
                {"logit_bias", n => { LogitBias = n.GetObjectValue<CreateAnswerRequest_logit_bias>(CreateAnswerRequest_logit_bias.CreateFromDiscriminatorValue); } },
                {"logprobs", n => { Logprobs = n.GetIntValue(); } },
                {"max_rerank", n => { MaxRerank = n.GetIntValue(); } },
                {"max_tokens", n => { MaxTokens = n.GetIntValue(); } },
                {"model", n => { Model = n.GetStringValue(); } },
                {"n", n => { N = n.GetIntValue(); } },
                {"question", n => { Question = n.GetStringValue(); } },
                {"return_metadata", n => { ReturnMetadata = n.GetBoolValue(); } },
                {"return_prompt", n => { ReturnPrompt = n.GetBoolValue(); } },
                {"search_model", n => { SearchModel = n.GetStringValue(); } },
                {"stop", n => { Stop = n.GetObjectValue<Answers>(Answers.CreateFromDiscriminatorValue); } },
                {"temperature", n => { Temperature = n.GetDoubleValue(); } },
                {"user", n => { User = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("documents", Documents);
            writer.WriteCollectionOfPrimitiveValues<string>("examples", Examples);
            writer.WriteStringValue("examples_context", ExamplesContext);
            writer.WriteStringValue("file", File);
            writer.WriteObjectValue<CreateAnswerRequest_logit_bias>("logit_bias", LogitBias);
            writer.WriteIntValue("logprobs", Logprobs);
            writer.WriteIntValue("max_rerank", MaxRerank);
            writer.WriteIntValue("max_tokens", MaxTokens);
            writer.WriteStringValue("model", Model);
            writer.WriteIntValue("n", N);
            writer.WriteStringValue("question", Question);
            writer.WriteBoolValue("return_metadata", ReturnMetadata);
            writer.WriteBoolValue("return_prompt", ReturnPrompt);
            writer.WriteStringValue("search_model", SearchModel);
            writer.WriteObjectValue<Answers>("stop", Stop);
            writer.WriteDoubleValue("temperature", Temperature);
            writer.WriteStringValue("user", User);
        }
        /// <summary>
        /// Composed type wrapper for classes string, string
        /// </summary>
        public class Answers : IAdditionalDataHolder, IParsable {
            /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
            public IDictionary<string, object> AdditionalData { get; set; }
            /// <summary>Serialization hint for the current wrapper.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? SerializationHint { get; set; }
#nullable restore
#else
            public string SerializationHint { get; set; }
#endif
            /// <summary>Composed type representation for type string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? String { get; set; }
#nullable restore
#else
            public string String { get; set; }
#endif
            /// <summary>
            /// Instantiates a new answers and sets the default values.
            /// </summary>
            public Answers() {
                AdditionalData = new Dictionary<string, object>();
            }
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static Answers CreateFromDiscriminatorValue(IParseNode parseNode) {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new Answers();
                if(parseNode.GetStringValue() is string stringValue) {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            public IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public void Serialize(ISerializationWriter writer) {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(String != null) {
                    writer.WriteStringValue(null, String);
                }
                writer.WriteAdditionalData(AdditionalData);
            }
        }
    }
}
